services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: phpclass
    # links:
    # - redis

  # redis:
  #   container_name: phpredis
  #   build: .docker/redis
